# play
- hosts: localhost
  become: True
  vars:
    syslog_host: "localhost"
    syslog_port: "514"
  tasks:
    - name: Install required system packages
      package:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'python3-setuptools']

    - name: Add Docker GPG Key (Ubuntu)
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: ansible_distribution == "Ubuntu"

    # - name: Add Docker GPG Key (CentOS)
    #   rpm_key:
    #     url: https://download.docker.com/linux/centos/docker-ce.repo
    #     state: present
    #   when: ansible_distribution == "CentOS"

    - name: Add Docker Repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
      when: ansible_distribution == "Ubuntu"

    - name: Add Docker Repo
      yum_repository:
        repo: https://download.docker.com/linux/centos/docker-ce.repo
        state: present
      when: ansible_distribution == "CentOS"

    - name: Update package manager and install docker-ce
      apt:
        update_cache: yes
        name: docker-ce
        state: latest

    - name: Update package manager and install docker-ce
      yum:
        update_cache: yes
        name: docker-ce
        state: latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Configure syslog driver
      template:
        src: daemon.json.j2
        dest: daemon.json

    - name: Start docker service
      service:
        name: docker
        state: started
